/**
 * Build an idempotent SQL seed file from seed/live-performances.json.
 *
 * Re-running is safe: events/places/people upsert on their unique keys, and an
 * event's acts/sources are replaced (never duplicated). Annotations and media
 * are never touched.
 *
 * Usage: `npm run seed:local` (runs this, then applies via wrangler d1 execute).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { normalizeTime } from "../src/shared/date";
import { eventSlug } from "../src/server/lib/slug";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

interface RawPerformance {
  title: string;
  date: string;
  time: string;
  venue: string;
  acts: string[];
  sources: string[];
  notes: string;
  description: string;
  confidence: string;
}

const BAND_MEMBERS = ["Will", "McIan", "Brent", "Eddie", "Sean", "Ryan"];

function sql(value: string | number | null | undefined): string {
  if (value === null || value === undefined || value === "") return "NULL";
  if (typeof value === "number") return String(value);
  return `'${value.replace(/'/g, "''")}'`;
}

function confidenceValue(raw: string): string {
  const c = raw?.toLowerCase();
  return c === "low" || c === "medium" || c === "high" ? c : "medium";
}

function isUrl(source: string): boolean {
  return /^https?:\/\//i.test(source.trim());
}

function main() {
  const raw: RawPerformance[] = JSON.parse(
    readFileSync(join(root, "seed", "live-performances.json"), "utf8"),
  );

  const lines: string[] = [];
  lines.push("-- Generated by scripts/seed.ts - do not edit by hand.");
  lines.push("PRAGMA foreign_keys = ON;");
  lines.push("");

  // People (band members) --------------------------------------------------
  lines.push("-- Band members");
  for (const name of BAND_MEMBERS) {
    lines.push(
      `INSERT INTO people (display_name) SELECT ${sql(name)} WHERE NOT EXISTS (SELECT 1 FROM people WHERE display_name = ${sql(name)});`,
    );
  }
  lines.push("");

  const usedSlugs = new Set<string>();
  const venues = new Set<string>();

  for (const rec of raw) {
    const venue = rec.venue?.trim();
    if (venue) venues.add(venue);
  }

  // Places -----------------------------------------------------------------
  lines.push("-- Places (venues)");
  for (const venue of venues) {
    lines.push(
      `INSERT INTO places (name, status) VALUES (${sql(venue)}, 'unknown') ON CONFLICT(name) DO NOTHING;`,
    );
  }
  lines.push("");

  // Events -----------------------------------------------------------------
  for (const rec of raw) {
    const title = rec.title?.trim() || "Untitled event";
    const date = rec.date?.trim() || null;

    let slug = eventSlug(title, date);
    let n = 2;
    while (usedSlugs.has(slug)) slug = `${eventSlug(title, date)}-${n++}`;
    usedSlugs.add(slug);

    const time = normalizeTime(rec.time);
    const venue = rec.venue?.trim() || null;
    const summary = [rec.notes?.trim(), rec.description?.trim()]
      .filter(Boolean)
      .join("\n\n");
    const confidence = confidenceValue(rec.confidence);

    const placeSubquery = venue
      ? `(SELECT id FROM places WHERE name = ${sql(venue)})`
      : "NULL";
    const eventSubquery = `(SELECT id FROM events WHERE slug = ${sql(slug)})`;

    lines.push(`-- ${title} (${date ?? "unknown date"})`);
    lines.push(
      `INSERT INTO events (slug, name, event_type, event_date, event_time, date_precision, place_id, summary, confidence)\n` +
        `VALUES (${sql(slug)}, ${sql(title)}, 'performance', ${sql(date)}, ${sql(time)}, 'exact', ${placeSubquery}, ${sql(summary)}, '${confidence}')\n` +
        `ON CONFLICT(slug) DO UPDATE SET name=excluded.name, event_date=excluded.event_date, event_time=excluded.event_time, place_id=excluded.place_id, summary=excluded.summary, confidence=excluded.confidence, modified_on=CURRENT_TIMESTAMP;`,
    );

    // Acts (skip the band itself) - replace to stay idempotent.
    lines.push(
      `DELETE FROM event_acts WHERE event_id = ${eventSubquery};`,
    );
    const acts = (rec.acts ?? [])
      .map((a) => a.trim())
      .filter((a) => a && !/^the conglomerate$/i.test(a));
    for (const act of [...new Set(acts)]) {
      lines.push(
        `INSERT INTO event_acts (event_id, name, billing_role) VALUES (${eventSubquery}, ${sql(act)}, 'unknown');`,
      );
    }

    // Sources - replace to stay idempotent.
    lines.push(
      `DELETE FROM event_sources WHERE event_id = ${eventSubquery};`,
    );
    for (const source of rec.sources ?? []) {
      const s = source.trim();
      if (!s) continue;
      if (isUrl(s)) {
        lines.push(
          `INSERT INTO event_sources (event_id, source_type, url) VALUES (${eventSubquery}, 'url', ${sql(s)});`,
        );
      } else {
        lines.push(
          `INSERT INTO event_sources (event_id, source_type, description) VALUES (${eventSubquery}, 'text', ${sql(s)});`,
        );
      }
    }
    lines.push("");
  }

  const outPath = join(root, "seed", "seed.generated.sql");
  writeFileSync(outPath, lines.join("\n"));
  console.log(
    `Seed SQL written to ${outPath} (${raw.length} events, ${venues.size} places).`,
  );
}

main();
